apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: v-ambulance-ufe-content
spec:
  microFrontend: v-ambulance-ufe
  element: v-ambulance-wl-app
  attributes:
    - name: base-path
      value: /v-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?v-ambulance-wl(/.*)?$"
